valuenetwork/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

from django.contrib import databrowse
from valuenetwork.valueaccounting.models import *

databrowse.site.register(
    AgentType,
    AssociationType,
    AgentAssociation,
    Category,
    EconomicAgent, 
    EconomicResourceType,
    EconomicResource,
    AgentResourceType, 
    ProcessType, 
    ProcessTypeResourceType,
    Project,
    ResourceRelationship,
    Commitment,
    EconomicEvent,
    EventType,
    Process,
    Unit,
    CachedEventSummary,
)

urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "homepage.html"}, name="home"),
    url(r"^admin/", include(admin.site.urls)),

    url(r"^account/", include("account.urls")),
    url(r"^accounting/", include("valuenetwork.valueaccounting.urls")),
    (r'^databrowse/(.*)', databrowse.site.root),
    url(r'^add/(?P<model_name>\w+)/?$', 'valuenetwork.tekextensions.views.add_new_model'),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

valuenetwork/valueaccounting/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns("",
    url(r"^projects/$", 'valuenetwork.valueaccounting.views.projects', name="projects"),
    url(r"^resources/$", 'valuenetwork.valueaccounting.views.resource_types', name="resource_types"),
    url(r"^contributions/(?P<project_id>\d+)/$", 'valuenetwork.valueaccounting.views.contributions', name="contributions"),
    url(r"^contributionhistory/(?P<agent_id>\d+)/$", 'valuenetwork.valueaccounting.views.contribution_history', name="contribution_history"),
    url(r"^logtime/$", 'valuenetwork.valueaccounting.views.log_time', name="log_time"),
    url(r"^value/(?P<project_id>\d+)/$", 'valuenetwork.valueaccounting.views.value_equation', name="value_equation"),
    url(r"^xbomfg/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.extended_bill', name="extended_bill"),
    url(r"^edit-xbomfg/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.edit_extended_bill', name="edit_extended_bill"),
    url(r"^network/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.network', name="network"),
    url(r"^timeline/$", 'valuenetwork.valueaccounting.views.timeline', name="timeline"),
    url(r"^jsontimeline/$", 'valuenetwork.valueaccounting.views.json_timeline', name="json_timeline"),
    url(r"^create-processtype-input/(?P<process_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.create_process_type_input', 
        name="create_process_type_input"),
    url(r"^create-processtype-feature/(?P<process_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.create_process_type_feature', 
        name="create_process_type_feature"),
    url(r"^change-feature/(?P<feature_id>\d+)/$", 'valuenetwork.valueaccounting.views.change_feature', 
        name="change_feature"),
    url(r"^delete-feature-confirmation/(?P<feature_id>\d+)/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.delete_feature_confirmation', 
        name="delete_feature_confirmation"),
    url(r"^delete-feature/(?P<feature_id>\d+)/$", 'valuenetwork.valueaccounting.views.delete_feature', 
        name="delete_feature"),
    url(r"^create-options-for-feature/(?P<feature_id>\d+)/$", 'valuenetwork.valueaccounting.views.create_options_for_feature', 
        name="create_options_for_feature"),
    url(r"^change-options-for-feature/(?P<feature_id>\d+)/$", 'valuenetwork.valueaccounting.views.change_options_for_feature', 
        name="change_options_for_feature"),
    url(r"^change-processtype-input/(?P<input_id>\d+)/$", 'valuenetwork.valueaccounting.views.change_process_type_input', 
        name="change_process_type_input"),
    url(r"^create-agent-resource-type/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.create_agent_resource_type', 
        name="create_agent_resource_type"),
    url(r"^change-agent-resource-type/(?P<agent_resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.change_agent_resource_type', 
        name="change_agent_resource_type"),
    url(r"^create-process-type-for-resource-type/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.create_process_type_for_resource_type', 
        name="create_process_type_for_resource_type"),
    url(r"^change-process-type/(?P<process_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.change_process_type', 
        name="change_process_type"),
    url(r"^change-resource-type/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.change_resource_type', 
        name="change_resource_type"),
    url(r"^create-resource-type/$", 'valuenetwork.valueaccounting.views.create_resource_type', 
        name="create_resource_type"),
    url(r"^delete-resource-type/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.delete_resource_type', 
        name="delete_resource_type"),
    url(r"^delete-resource-type-confirmation/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.delete_resource_type_confirmation', 
        name="delete_resource_type_confirmation"),
    url(r"^delete-process-type/(?P<process_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.delete_process_type', 
        name="delete_process_type"),
    url(r"^delete-process-type-confirmation/(?P<process_type_id>\d+)/(?P<resource_type_id>\d+)/$", 
        'valuenetwork.valueaccounting.views.delete_process_type_confirmation', 
        name="delete_process_type_confirmation"),
    url(r"^delete-process-input/(?P<process_input_id>\d+)/(?P<resource_type_id>\d+)/$", 
        'valuenetwork.valueaccounting.views.delete_process_input', 
        name="delete_process_input"),
    url(r"^delete-source/(?P<source_id>\d+)/(?P<resource_type_id>\d+)/$", 
        'valuenetwork.valueaccounting.views.delete_source', 
        name="delete_source"),
    url(r"^json-resourcetype-unit/(?P<resource_type_id>\d+)/$", 'valuenetwork.valueaccounting.views.json_resource_type_unit', 
        name="json_resource_type_unit"),
    url(r"^create-order/$", 'valuenetwork.valueaccounting.views.create_order', name="create_order"),
    url(r"^order-schedule/(?P<order_id>\d+)/$", 'valuenetwork.valueaccounting.views.order_schedule', name="order_schedule"),
    url(r"^delete-order/(?P<order_id>\d+)/$", 'valuenetwork.valueaccounting.views.delete_order', name="delete_order"),
    url(r"^delete-order-confirmation/(?P<order_id>\d+)/$", 'valuenetwork.valueaccounting.views.delete_order_confirmation', name="delete_order_confirmation"),
    url(r"^demand/$", 'valuenetwork.valueaccounting.views.demand', name="demand"),
    url(r"^supply/$", 'valuenetwork.valueaccounting.views.supply', name="supply"),
    url(r"^work/$", 'valuenetwork.valueaccounting.views.work', name="work"),

)

valuenetwork/tekextensions/models.py
from django.db import models

# Create your models here.

valuenetwork/valueaccounting/models.py
import datetime
import re
from decimal import *

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.contenttypes.models import ContentType
from django.db.models import Q
from django.template.defaultfilters import slugify

from easy_thumbnails.fields import ThumbnailerImageField


"""Models based on REA

These models are based on the Bill McCarthy's Resource-Event-Agent accounting model:
https://www.msu.edu/~mccarth4/
http://en.wikipedia.org/wiki/Resources,_events,_agents_(accounting_model)

REA is also the basis for ISO/IEC FDIS 15944-4 ACCOUNTING AND ECONOMIC ONTOLOGY
http://global.ihs.com/doc_detail.cfm?item_s_key=00495115&item_key_date=920616

"""

def unique_slugify(instance, value, slug_field_name='slug', queryset=None,
                   slug_separator='-'):
    """
    Calculates a unique slug of ``value`` for an instance.

    ``slug_field_name`` should be a string matching the name of the field to
    store the slug in (and the field to check against for uniqueness).

    ``queryset`` usually doesn't need to be explicitly provided - it'll default
    to using the ``.all()`` queryset from the model's default manager.
    """
    slug_field = instance._meta.get_field(slug_field_name)

    slug = getattr(instance, slug_field.attname)
    slug_len = slug_field.max_length

    # Sort out the initial slug. Chop its length down if we need to.
    slug = slugify(value)
    if slug_len:
        slug = slug[:slug_len]
    slug = _slug_strip(slug, slug_separator)
    original_slug = slug

    # Create a queryset, excluding the current instance.
    if not queryset:
        queryset = instance.__class__._default_manager.all()
        if instance.pk:
            queryset = queryset.exclude(pk=instance.pk)

    # Find a unique slug. If one matches, at '-2' to the end and try again
    # (then '-3', etc).
    next = 2
    while not slug or queryset.filter(**{slug_field_name: slug}):
        slug = original_slug
        end = '-%s' % next
        if slug_len and len(slug) + len(end) > slug_len:
            slug = slug[:slug_len-len(end)]
            slug = _slug_strip(slug, slug_separator)
        slug = '%s%s' % (slug, end)
        next += 1

    setattr(instance, slug_field.attname, slug)


def _slug_strip(value, separator=None):
    """
    Cleans up a slug by removing slug separator characters that occur at the
    beginning or end of a slug.

    If an alternate separator is used, it will also replace any instances of
    the default '-' separator with the new separator.
    """
    if separator == '-' or not separator:
        re_sep = '-'
    else:
        re_sep = '(?:-|%s)' % re.escape(separator)
        value = re.sub('%s+' % re_sep, separator, value)
    return re.sub(r'^%s+|%s+$' % (re_sep, re_sep), '', value)

CATEGORIZATION_CHOICES = (
    ('Anything', _('Anything')),
    ('EconomicResourceType', _('EconomicResourceType')),
)


class Category(models.Model):
    name = models.CharField(_('name'), max_length=128)
    applies_to = models.CharField(_('applies to'), max_length=128, 
        choices=CATEGORIZATION_CHOICES)
    description = models.TextField(_('description'), blank=True, null=True)
    orderable = models.BooleanField(_('orderable'), default=False,
        help_text=_('Should appear in Order form?'))

    class Meta:
        verbose_name_plural = 'categories'
        ordering = ('name',)
     
    def __unicode__(self):
        return self.name


UNIT_TYPE_CHOICES = (
    ('length', _('length')),
    ('quantity', _('quantity')),
    ('time', _('time')),
    ('value', _('value')),
    ('volume', _('volume')),
    ('weight', _('weight')),
    ('ip', _('ip')),
)
 
class Unit(models.Model):
    unit_type = models.CharField(_('unit type'), max_length=12, choices=UNIT_TYPE_CHOICES)
    abbrev = models.CharField(_('abbreviation'), max_length=8)
    name = models.CharField(_('name'), max_length=64)
    symbol = models.CharField(_('symbol'), max_length=1, blank=True)

    class Meta:
        ordering = ('name',)
     
    def __unicode__(self):
        return self.name

    @classmethod
    def add_new_form(cls):
        return None


ACTIVITY_CHOICES = (
    ('active', _('active contributor')),
    ('affiliate', _('close affiliate')),
    ('inactive', _('inactive contributor')),
    ('agent', _('active agent')),
    ('passive', _('passive agent')),
    ('external', _('external agent')),
)

SIZE_CHOICES = (
    ('individual', _('individual')),
    ('org', _('organization')),
    ('network', _('network')),
    ('team', _('project team')),
    ('community', _('community')),
)

class AgentType(models.Model):
    name = models.CharField(_('name'), max_length=128)
    parent = models.ForeignKey('self', blank=True, null=True, 
        verbose_name=_('parent'), related_name='sub-agents', editable=False)
    member_type = models.CharField(_('member type'), 
        max_length=12, choices=ACTIVITY_CHOICES,
        default='active')
    party_type = models.CharField(_('party type'), 
        max_length=12, choices=SIZE_CHOICES,
        default='individual')

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name


class EconomicAgent(models.Model):
    name = models.CharField(_('name'), max_length=255)
    nick = models.CharField(_('ID'), max_length=32, unique=True)
    url = models.CharField(_('url'), max_length=255, blank=True)
    agent_type = models.ForeignKey(AgentType,
        verbose_name=_('agent type'), related_name='agents')
    description = models.TextField(_('description'), blank=True, null=True)
    address = models.CharField(_('address'), max_length=255, blank=True)
    email = models.EmailField(_('email address'), max_length=96, blank=True, null=True)
    latitude = models.FloatField(_('latitude'), default=0.0, blank=True, null=True)
    longitude = models.FloatField(_('longitude'), default=0.0, blank=True, null=True)
    reputation = models.DecimalField(_('reputation'), max_digits=8, decimal_places=2, 
        default=Decimal("0.00"))
    photo = ThumbnailerImageField(_("photo"),
        upload_to='photos', blank=True, null=True)
    slug = models.SlugField(_("Page name"), editable=False)
    created_date = models.DateField(_('created date'))
    
    class Meta:
        ordering = ('nick',)
    
    def __unicode__(self):
        return self.nick
    
    def save(self, *args, **kwargs):
        unique_slugify(self, self.nick)
        super(EconomicAgent, self).save(*args, **kwargs)

    def seniority(self):
        return (datetime.date.today() - self.created_date).days

    def node_id(self):
        return "-".join(["Agent", str(self.id)])

    def color(self):
        return "green"

    def produced_resource_type_relationships(self):
        return self.resource_types.filter(relationship__direction='out')

    def produced_resource_types(self):
        return [ptrt.resource_type for ptrt in self.produced_resource_type_relationships()]

    def consumed_resource_type_relationships(self):
        return self.resource_types.filter(relationship__direction='in')

    def consumed_resource_types(self):
        return [ptrt.resource_type for ptrt in self.consumed_resource_type_relationships()]

    def xbill_parents(self):
        return self.produced_resource_type_relationships()

    def xbill_children(self):
        return []

    def xbill_class(self):
        return "economic-agent"  


class AssociationType(models.Model):
    name = models.CharField(_('name'), max_length=128)


class AgentAssociation(models.Model):
    from_agent = models.ForeignKey(EconomicAgent,
        verbose_name=_('from'), related_name='associations_from')
    to_agent = models.ForeignKey(EconomicAgent,
        verbose_name=_('to'), related_name='associations_to')
    association_type = models.ForeignKey(AssociationType,
        verbose_name=_('association type'), related_name='associations')
    description = models.TextField(_('description'), blank=True, null=True)


RESOURCE_EFFECT_CHOICES = (
    ('+', _('increase')),
    ('-', _('decrease')),
    ('x', _('transfer')), #means - for from_agent, + for to_agent
    ('=', _('no effect')),
)

class EventType(models.Model):
    name = models.CharField(_('name'), max_length=128)
    resource_effect = models.CharField(_('resource effect'), 
        max_length=12, choices=RESOURCE_EFFECT_CHOICES)
    unit_type = models.CharField(_('unit type'), max_length=12, choices=UNIT_TYPE_CHOICES)
    slug = models.SlugField(_("Page name"), editable=False)

    class Meta:
        ordering = ('name',)

    def __unicode__(self):
        return self.name

    def save(self, *args, **kwargs):
        unique_slugify(self, self.name)
        super(EventType, self).save(*args, **kwargs)


""" design_issue:
    Materiality is probably part of a Category model.

"""

MATERIALITY_CHOICES = (
    ('material', _('material')),
    ('intellectual', _('intellectual')),
    ('work', _('work')),
    ('tool', _('tool')),
)

class EconomicResourceTypeManager(models.Manager):

    def types_of_work(self):
        return EconomicResourceType.objects.filter(materiality="work")



class EconomicResourceType(models.Model):
    name = models.CharField(_('name'), max_length=128)    
    parent = models.ForeignKey('self', blank=True, null=True, 
        verbose_name=_('parent'), related_name='children', editable=False)
    category = models.ForeignKey(Category, blank=True, null=True, 
        verbose_name=_('category'), related_name='resource_types',
        limit_choices_to=Q(applies_to='Anything') | Q(applies_to='EconomicResourceType'))
    materiality = models.CharField(_('materiality'), 
        max_length=12, choices=MATERIALITY_CHOICES,
        default='material')
    unit = models.ForeignKey(Unit, blank=True, null=True,
        verbose_name=_('unit'), related_name="resource_units")

valuenetwork/templates/valueaccounting/agent_contributions.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Contributions from " %} {{ agent }}{% endblock %}

{% block extra_head %}
<style>

	tr.even td 
	{
		color:#000000;
		background-color:#EAF2D3;
	}

	th
	{
		background-color:#C8D6E8;
	}

</style>

{% endblock %}

{% block body_class %}projects{% endblock %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}
	<div>
		<h1>{% trans "Contributions from " %} {{ agent }}</h1>
		<table class="table table-bordered table-hover table-condensed" >
			<thead>
				<th>Date</th>
				<th>Type</th>
				<th>Project</th>
				<th>Resource Type</th>
				<th>Qty</th>
				<th>Unit</th>
				<th>URL</th>
				<th>Description</th>
			</thead>
			<tbody>	
				{% for event in events %}
					<tr class="{% cycle 'odd' 'even' %}">
						<td>{{ event.event_date }}</td>
						<td>{{ event.event_type }}</td>
						<td>{{ event.project }}</td>
						<td>{{ event.resource_type }}</td>
						<td style="text-align: right;" >{{ event.quantity_formatted }}</td>
						<td>{{ event.unit_of_quantity }}</td>
						<td>
							{% if event.url %}
								<a href="{{ event.url }}" target="_blank">Open</a>
							{% endif %}
						</td>
						<td>{{ event.description|urlize }}</td>
					</tr>
				{% endfor %}
			<tbody>	
		</table>
<div class="pagination">
    <span class="step-links">
        {% if events.has_previous %}
            <a href="?page={{ events.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ events.number }} of {{ events.paginator.num_pages }}.
        </span>

        {% if events.has_next %}
            <a href="?page={{ events.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

	</div>
    </div>
{% endblock %}

valuenetwork/templates/valueaccounting/create_order.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}

{% block head_title %}{% trans "Create Order" %}{% endblock %}

{% block extra_head %}

<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />

<style>

	tr.even td 
	{
		color:#000000;
		background-color:#EAF2D3;
	}

	th
	{
		background-color:#C8D6E8;
	}

.item-description
{
    height: 64px;
}

#id_description
{
  width: 53em;
}

</style>

{% endblock %}

{% block body_class %}projects{% endblock %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}
	<div>

		<legend>{% trans "Create Order" %}</legend>

		<form method="POST" action="">
			{% csrf_token %}
			<div class="row-fluid">
				<div class="span3 control-group">
					<b>Provider:</b></br>
					{{ order_form.provider }}
				</div>
				<div class="span3 control-group">
					<b>Receiver:</b></br>
					{{ order_form.receiver }}
				</div>
				<div class="span2 control-group">
					<b>Due date:</b></br>
					{{ order_form.due_date }}
				</div>
			</div>
			<div class="row-fluid">
				<div class="span8 control-group">
						<b>Notes:</b></br>
						{{ order_form.description }}
				</div>
				<div class="form-actions span2">
		        	<button class="btn btn-primary" type="submit">Submit</button>
		    	</div>
			</div>

			<table style="width: 100%;" class="table table-bordered table-hover table-condensed" >
				<thead>
					<th>Resource</th>
					<th>Options</th>
					<th>Qty</th>
					<th>Unit</th>
					<th>Notes</th>
				</thead>
				<tbody>	
					{% for form in item_forms %}
						{{ form.resource_type_id }}
						<tr class="{% cycle 'odd' 'even' %}">
							<td>{{ form.resource_type.name }}</td>
							<td>
								{% for feature in form.features %}
									{{ feature.feature.name }} {{ feature.options }} 
								{% endfor %}
							</td>
							<td>{{ form.quantity }}</td>
							<td>{{ form.resource_type.unit }}</td>
							<td>{{ form.description }}</td>
						</tr>
					{% endfor %}
				<tbody>	
			</table>
			<div class="form-actions">
		       	<button class="btn btn-primary" type="submit">Submit</button>
		   	</div>

		</form>

	</div>
    </div>
{% endblock %}
{% block extra_script %}
<script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
{% endblock %}

{% block extra_body %}
	{{ block.super }}

    <script type="text/javascript">

	$(document).ready(function(){

		$(function() {
        	$( "#id_due_date" ).datepicker({ dateFormat: "yy-mm-dd" });
    	});

	}); // end document.ready
    </script>

{% endblock %}

valuenetwork/templates/valueaccounting/demand.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Demand" %}{% endblock %}

{% block body_class %}projects{% endblock %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}
	<div>
		<legend>{% trans "Demand" %}</legend>
			{% if user.is_authenticated %}
				<p>
					<a class="btn" href="{% url create_order %}">Create Order</a>
				</p>
			{% endif %}
			{% if orders %}
		        <h3 style="margin-bottom: 4px;" >Open Orders:</h3>
				<ul>
				    {% for order in orders %}
						<li>
                            <a href="{% url order_schedule order_id=order.id %}">{{ order }}</a> 
                            <a class="btn btn-warning" href="{% url delete_order_confirmation order_id=order.id %}">Delete</a>
                        </li>
					{% endfor %}
				</ul>
			{% endif %}


	</div>
    </div>
{% endblock %}

valuenetwork/templates/valueaccounting/network.html
{% extends "site_base.html" %}

{% load i18n %}
{% load thumbnail %}

{% block head_title %}{% trans "Value Network for " %} {{ resource_type }}{% endblock %}

{% block extra_head %}

{% endblock %}

{% block body_class %}projects{% endblock %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}
	<div>
		<h1>{% trans "Value Network for " %} {{ resource_type }}
			{% if resource_type.photo %}
			<img src="{% thumbnail resource_type.photo photo_size %}" />
			{% endif %}
		</h1>
		<div>
			<div style="float: left;">
				<button id="redraw" onclick="redraw();">redraw</button> or just drag stuff around...
			</div>
			<div style="float: right;">
				<span style="color:blue;">Blue oval = Process</span></br>
				<span style="color:red;">Red rectangle = Resource</span></br>
				<span style="color:green;">Green rectange = Agent</span>
			</div>
			<div style="clear:both;"></div>
		</div>

		<div id="canvas" style="width:100%; height:600px;" ></div>

	</div>


	{% include "valueaccounting/_network_diagram.html" %}

    </div>
{% endblock %}

valuenetwork/templates/valueaccounting/order_delete_confirmation.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Confirm deletion of " %}{{ order }}{% endblock %}

{% block body_class %}projects{% endblock %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}
	<div>
		<legend>{% trans "Are you sure you want to delete " %}{{ order }}?</legend>
		
		<h3>{% trans "The following objects will be also deleted" %}:</h3>

            <h3 style="margin-top: 1em;" >Order Items:</h3>
			<ul>
		        {% for item in order.producing_commitments %}
					<li>{{ item.quantity }} {{ item.unit_of_quantity }} {{ item.resource_type }} {{ item.feature_label }}</li>
				{% endfor %}
			</ul>

			<div class="row-fluid">

				<div class="span6">
					<h3 style="margin-bottom: 4px;" >Production Schedule:</h3>
					{% for item in sked %}
						<p style="margin-left:{{ item.depth }}em" >
							<b>{{ item.label }}:</b> {{ item }} 
						</p>
					{% endfor %}
				</div>

				<div class="span6">

					<h3 style="margin-bottom: 4px;" >Material Requirements:</h3>
					{% for item in reqs %}
						<p>
							<b>{{ item.resource_type.name }}:</b> {{ item.quantity }} {{ item.unit_of_quantity }} due {{ item.due_date }}
						</p>
						<p style="margin-left: 2em;">
							for process: {{ item.process }}
						</p>
						{% for source in item.resource_type.producing_agent_relationships %}
							<p style="margin-left: 2em;">
								<b>Source:</b> {{ source.agent.name }} Lead time: {{ source.lead_time }} days
							</p>
						{% endfor %}
					{% endfor %}

					<h3 style="margin-bottom: 4px;" >Work Requirements:</h3>
					{% for item in work %}
						<p>
							<b>{{ item.resource_type.name }}:</b> {{ item.quantity }} {{ item.unit_of_quantity }} due {{ item.due_date }}
						</p>
						<p style="margin-left: 2em;">
							for process: {{ item.process }}
						</p>
						{% for source in item.resource_type.producing_agent_relationships %}
							<p style="margin-left: 2em;">
								<b>Source:</b> {{ source.agent.name }}
							</p>
						{% endfor %}
					{% endfor %}

					<h3 style="margin-bottom: 4px;" >Tool Requirements:</h3>
					{% for item in tools %}
						<p>
							<b>{{ item.resource_type.name }}:</b> {{ item.quantity }} {{ item.unit_of_quantity }} due {{ item.due_date }}
						</p>
						<p style="margin-left: 2em;">
							for process: {{ item.process }}
						</p>
						{% for source in item.resource_type.producing_agent_relationships %}
							<p style="margin-left: 2em;">
								<b>Source:</b> {{ source.agent.name }} Lead time: {{ source.lead_time }} days
							</p>
						{% endfor %}
					{% endfor %}

				</div>

			</div>

		<div>
	<form style="display: inline;" action="{% url delete_order order_id=order.id %}" method="POST">
		{% csrf_token %}
    		<input type="submit" value="{% trans 'Delete' %}" class="btn btn-warning" />
	</form>
	<form style="display: inline;" action="{% url demand %}" method="GET">
    		<input type="submit" value="{% trans 'Cancel' %}" class="btn btn-info" />
    </form>

	</div>

	</div>
    </div>
{% endblock %}